instance: default
from: mysql
to: stdio
mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  passwd: 123456
rules:
  master_slave_db:
    user: 1
    user2: 1
redis:
  host: 127.0.0.1
  port: 26379
  passwd:
  db: 0
